### ISSUE TITLE
[1.20.1] Perspective change button conflict

### ISSUE THREAD

**Issue by polykatt** [Jeryn99/MC-Gliders#66] opened 2024-06-05 05:21 UTC
The perspective change button conflicts with the operator inventory button in the options menu. So the perspective change cannot be toggled on as the operator inventory button that is overlayed on top of it is taking preference

**Comment by Jeryn99** [comment] 2024-06-05 09:01
Please ensure your issue does not already exist before creating a issue

Duplicate of https://github.com/Jeryn99/MC-Gliders/issues/52

**Closed** 2024-06-05 09:01 UTC
